config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'islands#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "my_bookings", to: 'bookings#my_bookings'
  get "my_islands", to: 'bookings#my_islands'
  resources :islands do
    resources :bookings, only: [:new, :create, :index]
     resources :reviews, only: [:show]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:new, :create]
    get "accept_booking", to: 'bookings#accept_booking'
    
  end
  resources :bookings, only: [:show] do
    resources :orders, only: [:show, :create] do
      resources :payments, only: [:new]
    end
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :orders
  belongs_to :user
  belongs_to :island
  has_many :reviews

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :guests, presence: true
  validates :total_price, presence: true

  def calculate_total_price
    @total_price = 200
  end
end

app/models/island.rb
class Island < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

   include PgSearch::Model
  pg_search_scope :search,
    against: [ :name, :location ],
    using: {
      tsearch: { prefix: true }
    }

  # REFERENCES
  has_one_attached :photo
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  # VALIDATIONS
  validates :name, presence: true
  validates :bedrooms, inclusion: { in: 0..10 }
  validates :location, presence: true
  validates :price_cents, presence: true
  validates :description, presence: true
  validates :max_guests, presence: true
  # validates :photo, presence: true
  # Stripe
  monetize :price_cents
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :booking
  monetize :amount_cents
end

app/models/review.rb
class Review < ApplicationRecord
  # REFERENCES
  belongs_to :booking
  # VALIDATIONS
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :islands
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # line below required! calls permitted parameters!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username photo])
  end

  def default_url_options
    { host: ENV["https://love-islands.herokuapp.com"] || "localhost:3000" }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @island = Island.find(params[:island_id])
    @booking = Booking.new
  end

  def create
    @island = Island.find(params[:island_id])
    @booking = Booking.new(booking_params)
    @booking.island = @island
    @booking.user = current_user

    @booking.total_price = @booking.calculate_total_price
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def my_bookings
    @bookings = current_user.bookings
    
  end

  def my_islands
    @islands = current_user.islands
    # @island = Island.find(params[:id])
  end

  def accept_booking
    @booking = Booking.find(params[:booking_id])
    @booking.status = params[:status]
    @booking.save
    redirect_to my_islands_path
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :guests)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  # INDEX

  def index
    @query = params[:query]
    if params[:query].present?
      @islands = Island.search(params[:query])
    else
    @islands = Island.all
    end
  end

  # NEW
  def new
    @island = Island.new
  end

  # SHOW
  def show
    @island = Island.find(params[:id])
    @markers = [
      {
        lat: @island.latitude,
        lng: @island.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { island: @island }),
        image_url: helpers.asset_url("Marker.png")
      }
    ]
  end

  # CREATE
  def create
    @island = Island.new(island_params)
    @island.user = current_user
    if @island.save
      redirect_to island_path(@island)
    else
      render :new
    end
  end

  # DESTROY
  def destroy
    @island = Island.find(params[:id])
    @island.destroy
    redirect_to islands_path
  end

  # EDIT
  def edit
    @island = Island.find(params[:id])
  end

  # UPDATE
  def update
    @island = Island.find(params[:id])
    if @island.update(island_params)
      redirect_to island_path(@island)
    else
      render :edit
    end
  end

  # PRIVATE PARAMS
  private

  def island_params
    params.require(:island).permit(:name, :location, :price_cents, :description, :max_guests, :photo, :bedrooms, :gym, :pool, :helicopter, :boat )

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    booking = Booking.find(params[:booking_id])
    final_price = (booking.check_out - booking.check_in).to_i * booking.island.price_cents
    order = Order.create!(booking: booking, amount: final_price, state: 'pending')

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: booking.island.name,

        #Fix this line, needs to send URL, not currently working
        images: [Cloudinary::Utils.cloudinary_url(booking.island.photo.key)],
        amount: final_price,
        currency: 'gbp',
        quantity: 1
      }],
      success_url: "http://localhost:3000/my_bookings",
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_booking_order_payment_path(booking, order)
  end

  def show
    # @booking = Booking.find(params[:booking_id])
    @order = Order.find(params[:id])
    # @order = @booking.orders.last
    # @order = current_user.orders.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @order = @booking.orders.last
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    # @review.user = current_user
    if @review.save
      redirect_to island_path(@booking.island)
    else
      render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h1>Enquire</h1>
      <p>Please enter your time of travel</p>

      <%= simple_form_for [@island, @booking] do |f| %>
        <%= f.input :check_in, html5: true %>
        <%= f.input :check_out, as: :date, html5: true %>
        <%= f.input :guests %>
        <div class="submit-button"><%= f.submit %></div>
      <% end %>
<!-- Fake payment method -->
    <!-- <hr>
    <h2>Total price: £2400 </h2>
    <hr>
    <h2>Payment</h2>
    <br>
      <form accept-charset="UTF-8" >
        <label for="type">Payment type:</label>
        <input name="type" type="text" placeholder="Visa" />
        <label for="card">Card Number:</label>
        <input name="card" type="text" placeholder="4534 4234 5604 2345"/>
        <label for="exp">Expire Date:</label>
        <input name="exp" type="text" placeholder="3/22"/>
        <br>
        <label for="cvv">CVV:</label>
        <input name="cvv" type="text" placeholder="***"/>
      </form>
    <hr> -->
    <!-- Fake payment method -->
<br>
<br>
<%= link_to "Back", island_path(@island)%>

  </div>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="banner-small p5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5d83b27ee1494900093a5627/master/pass/Cebu-&-Visayan-Islands,-Philippines_GettyImages-1074254788.jpg);">
  <div class="container">
    <h1>Manage my holidays</h1>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
        <% @bookings.each do |booking|%>
          <div class="card-product mt-3">
              <% if booking.island.photo.attached? %>
                <img class="d-none" src="<%= cl_image_path booking.island.photo.key %>" />
              <% else %>
                <img class="d-none" src="https://www.planetware.com/photos-large/SEY/best-islands-bora-bora.jpg" />
              <% end %>

              <div class="card-product-box">
                <div class="card-product-infos">
                  <h2><%= booking.island.name%></h2>

                  <p>Location: <strong><%= booking.island.location%></strong></p>
                  <p>Price: <strong><%= humanized_money_with_symbol(booking.island.price_cents)%></strong></p>


                </div>
                <div class="booking-request pr-4">
                  <% if booking.status == 'accepted' %>
                    <div id="book-request-confirmed">Booking accepted <i class="fas fa-check"></i><hr><%= link_to 'Leave Review', new_booking_review_path(booking),class: "btn-review" %></div>
                  <% elsif booking.status == 'rejected' %>
                    <div id="book-request-sent">Booking rejected</div>
                  <% else %>
                    <div id="book-request-sent">Booking pending</div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>


  <hr>
  <br>
    <h4>Rent a boat to improve your island experience!</h4>
    <a href="http://floatifyapp.herokuapp.com/" class="btn btn-primary mt-1">Rent now!</a>
  <br>
  <br>
  <hr>
  <%= link_to 'Back', islands_path%>
     </div>
  </div>
</div>

app/views/bookings/my_islands.html.erb
<div class="banner-small p5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5d83b27ee1494900093a5627/master/pass/Cebu-&-Visayan-Islands,-Philippines_GettyImages-1074254788.jpg);">
  <div class="container">
    <h1>Manage your island properties</h1>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 mt-3">
      <h2>Your booking requests</h2>
        <% @islands.each do |island|%>
          <% island.bookings.each do |booking| %>
            <div class="card-product mt-3">
              <% if booking.island.photo.attached? %>
                <img class="d-none" src="<%= cl_image_path booking.island.photo.key %>" />
              <% else %>
                <img class="d-none" src="https://www.planetware.com/photos-large/SEY/best-islands-bora-bora.jpg" />
              <% end %>

              <div class="card-product-box">
                <div class="card-product-infos">
                  <h2><%= island.name%></h2>
                  <p>Location:<strong><%= booking.island.location%></strong></p>
                  <p>Price:<strong><%= booking.island.price_cents%></strong></p>
                </div>
                <div class="booking-request pr-4">
                  <% if booking.status == 'pending' %>
                    <%= link_to 'Accept booking?', booking_accept_booking_path(booking, status:'accepted'), id: "book-button"  %>
                    <%= link_to 'Reject this booking?', booking_accept_booking_path(booking, status:'rejected'), id: "book-button-no-bg"  %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        </br>
      <%= link_to 'Back', islands_path %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
  <div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5d83b27ee1494900093a5627/master/pass/Cebu-&-Visayan-Islands,-Philippines_GettyImages-1074254788.jpg);">
  <div class="container">
    <h1>New Booking</h1>
  <p><%= @island.name %><p>
  </div>
</div>

<div class="container col-4">
<div class="form">
  <%= render 'form' %>
</div>
</div>

app/views/bookings/show.html.erb
<div class="banner-small p5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://www.ecomagazine.com/images/Newsletter/0_2019/Week_11-18-19/birdseyeview_ocean.jpg');">
  <div class="container">
    <h1>Booking summary for <%= @booking.island.name %></h1>
  </div>
</div>

<div class="container">


<h1>Congratulations, the <strong><%= @booking.island.name %> island</strong> is available<br> for the following dates!</h1>
  </br>

<p>Check-in date: <%= @booking.check_in.strftime("%d %b, %Y") %></p>
<p>Check-out date: <%= @booking.check_out.strftime("%d %b, %Y") %></p>
<p>Total: £<%= (@booking.check_out - @booking.check_in).to_i * @booking.island.price_cents %></p>
<br>
  <%= form_tag booking_orders_path(params[:id]) do %>
    <%= hidden_field_tag 'booking_id', @booking.id %>
    <%= submit_tag 'Book now!', class: 'btn btn-primary' %>
    <% end %>
  </br>
<%= link_to 'Back to Island', island_path(@booking.island) %>
</div>

app/views/islands/_img_form.html.erb
<%= simple_form_for(@island) do |f| %>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/islands/_info_window.html.erb
<div class="container">
  <h5><%= island.name %></h5>
  <ul class="show-features">
  <li><i class="material-icons mr-2">people</i>Island can have maximum <%= @island.max_guests %> <strong>Guests</strong>
  </li>
  <% if @island.pool == true %>
    <li><i class="material-icons mr-2">pool</i>This island has a <strong>Pool</strong></li>
  <% end %>

  <% if @island.gym == true %>
    <li><i class="material-icons mr-2">fitness_center</i>This island has a <strong>Gym</strong></li>
  <% end %>
  <% if @island.helicopter == true %>
    <li><i class="material-icons mr-2">flight_takeoff</i>This island has a <strong>Helicopter</strong></li>
  <% end %>
  <% if @island.boat == true %>
    <li><i class="material-icons mr-2">directions_boat</i>This island has a <strong>Boat</strong></li>
  <% end %>
</ul>
</div>

app/views/islands/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

<%= simple_form_for (@island) do |f| %>
<%= f.input :name %>
<%= f.input :location %>
<%= f.input :description %>
<%= f.input :max_guests %>
<%= f.input :price_cents %>
<%= f.input :photo, as: :file %>
<%= f.submit 'Update', class: 'btn btn-primary' %>
<% end %>

    </div>
  </div>
</div>

app/views/islands/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5d83b27ee1494900093a5627/master/pass/Cebu-&-Visayan-Islands,-Philippines_GettyImages-1074254788.jpg);">
  <div class="container">
    <h1>Find your <strong>perfect</strong> paradise destination!</h1>
    <p>Sort from hundreds of islands around the world.</p>
    </br>
    <div id="form-field"><%= form_tag islands_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    id: "form-field",
    placeholder: " 🔍 Find an island"
  %>
  <%= submit_tag "Search", id: "submit-button" %>
<% end %>
</div>

  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All available islands</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for '<%= @query %>'. We found <%= @islands.count %> islands out of our <%= Island.count %> on our website.</p>
      <% else %>
        <p>Displaying all <%= Island.count %> islands.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @islands.each do |island| %>
    <%= link_to island_path(island) do %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="island-card">
          <% if island.photo.attached? %>
            <div class="island-card-image" style="background-image: url('<%= cl_image_path island.photo.key %>')"></div>
          <% else %>
             <div class="island-card-image" style="background-image: url(<%= 'https://www.planetware.com/photos-large/SEY/best-islands-bora-bora.jpg' %>)"></div>
          <% end %>
          <div class="island-card-content">
            <div class="island-card-title">
              <h4><%= island.name %></h4>
            </div>
            <p><%= island.location %></p>
            <div class="flex">
              <div class="flex">
                <i class="material-icons mr-2">people</i><span><%= island.max_guests %></span>
              </div>
              <div class="flex ml-3">

                <p>Price per night: <%= humanized_money_with_symbol(island.price_cents) %></p>

              </div>
            </div>
          </div>

          <div class="island-card-button">
            <%= link_to 'Find out more', island_path(island) %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/islands/new.html.erb
  <div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5d83b27ee1494900093a5627/master/pass/Cebu-&-Visayan-Islands,-Philippines_GettyImages-1074254788.jpg);">
  <div class="container">
    <h1>Create New Island</h1>
  </div>
</div>

<div class="container p-5 mb-2 bg-white rounded" style="width: 600px;">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for (@island) do |f| %>
        <%= f.input :name, input_html: { class: "nice-class" } %>
        <%= f.input :location %>
        <%= f.input :description %>
        <%= f.input :max_guests %>
        <%= f.input :price_cents, label:"Price per night" %>
        <%= f.input :bedrooms, collection: (1..10) %>

        <div class="d-flex space-between justify-content-between flex-wrap">
          <%= f.input :gym, input_html: { class: "form-check-label"} %>
          <%= f.input :boat, input_html: { class: "form-check-label" } %>
          <%= f.input :pool, input_html: { class: "form-check-label" } %>
          <%= f.input :helicopter, input_html: { class: "form-check-label" } %>
        </div>

        <!-- Using single line instead of importing _img_form. -->
        <%= f.input :photo, as: :file%>
        <%= f.submit 'Add your Island', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
 </div>

app/views/islands/show.html.erb
<% if @island.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path @island.photo.key %>');">
    <div class="container">
      <h1>Welcome to <%= @island.location %></h1>
    </div>
  </div>
  <% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('https://img.theculturetrip.com/wp-content/uploads/2018/04/shutterstock_1050077834.jpg');">
    <div class="container">
      <h1>Welcome to <%= @island.location %></h1>
    </div>
  </div>
<% end %>

<div class ="container">
  <div class="row">
    <div class ="col-12 col-md-8">
      <h1 class="m-0"><%= @island.name %></h1>
      <p>Island hosted by <%= @island.user.first_name %></p>
      <p>Price per night: £<%= @island.price_cents %></p>
    </div>

    <div class="col-12 col-md-4">
      <% if current_user == @island.user %>
        <div class="container-buttons">
          <div id="edit-button"><%= link_to 'Edit', edit_island_path(@island) %></div>
          <span id="delete-button"><%= link_to 'Delete island', island_path(@island), method: 'delete', data: { confirm: "Are you sure?" } %></span>
        </div>
      <% else %>
        <%= link_to "Book Now", new_island_booking_path(@island), id: "book-button" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-8">
      <p style="color:lightgray">___________________________________________________________________________</p>
      </br>
      <h3>What to expect from your stay?</h3>
      </br>
      <p><%= @island.description %></p>

      <p style="color:lightgray">___________________________________________________________________________</p>

      <h4>Island Features</h4>

      <ul class="show-features">
        <li><i class="material-icons mr-2">people</i>Island can have maximum <%= @island.max_guests %> <strong>Guests</strong>
        </li>
      <li><i class="material-icons mr-2">bed</i>This island has <%= @island.bedrooms %> <strong>Bedrooms</strong></li>
        <% if @island.pool == true %>
          <li><i class="material-icons mr-2">pool</i>This island has a <strong>Pool</strong></li>
        <% end %>

        <% if @island.gym == true %>
          <li><i class="material-icons mr-2">fitness_center</i>This island has a <strong>Gym</strong></li>
        <% end %>
        <% if @island.helicopter == true %>
          <li><i class="material-icons mr-2">flight_takeoff</i>This island has a <strong>Helicopter</strong></li>
        <% end %>
        <% if @island.boat == true %>
          <li><i class="material-icons mr-2">directions_boat</i>This island has a <strong>Boat</strong></li>
        <% end %>
      </ul>

      <p style="color:lightgray">___________________________________________________________________________</p>
        <div class="mb-3"
          id="map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

      <h3>Reviews</h3>

      <div class="reviews">
        <% if @island.reviews.count == 0 %>
          <p>There are no reviews yet.</p>
          <% else %>
          <% @island.reviews.each do |review| %>

          <div class="review">
            <% if review.booking.user.photo.attached? %>
              <p><%= cl_image_tag review.booking.user.photo.key, class: "avatar" %> Review by <%= review.booking.user.first_name %></p>
            <% else %>
              <p><%= image_tag 'https://kitt.lewagon.com/placeholder/users/ssaunier', class: "avatar" %> Review by <%= review.booking.user.first_name %></p>
            <% end %>
            <div class="badge badge-primary badge-pill">
              <% counter = 0 %>
              <% 5.times do %>
                <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                <% counter += 1 %>
              <% end %>
            </div>
            <%= review.content %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.booking.island.image_url, width: '100%' %></div>
    <div class="col">
      <h1>Booking #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.booking.created_at.to_date %></li>
        <li><strong>ISLAND</strong> <%= @order.booking.island.name %></li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">


<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

 </div>
  </div>
</div>

app/views/shared/_banner.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5d83b27ee1494900093a5627/master/pass/Cebu-&-Visayan-Islands,-Philippines_GettyImages-1074254788.jpg);">
  <div class="container">
    <h1><%="#{current_user.first_name}" %>, find your <strong>perfect</strong> paradise destination!</h1>
    <p>Sort from hundreds of islands around the world.</p>
    </br>
    <div id="book-button"><%= link_to "Create New Island", new_island_path(@island) %></div>
</br>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-wrapper sticky">
  <div class="container">

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to islands_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/ddqpdj02o/image/upload/v1614093014/Love_islands_1_sagasx.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to "Home", islands_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Host an Island", new_island_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">

          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My islands", my_islands_path, class: "dropdown-item"  %>
            <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

</div>
</div>